package dev.pygloss.render

import com.intellij.ide.util.PropertiesComponent
import com.intellij.openapi.Disposable
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.application.ModalityState
import com.intellij.openapi.application.ReadAction
import com.intellij.openapi.editor.Caret
import com.intellij.openapi.editor.Editor
import com.intellij.openapi.editor.EditorFactory
import com.intellij.openapi.editor.event.DocumentEvent
import com.intellij.openapi.editor.event.DocumentListener
import com.intellij.openapi.editor.event.CaretEvent
import com.intellij.openapi.editor.event.CaretListener
import com.intellij.openapi.fileEditor.FileEditorManagerEvent
import com.intellij.openapi.fileEditor.FileEditorManagerListener
import com.intellij.openapi.fileEditor.FileDocumentManager
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.fileEditor.OpenFileDescriptor
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.TextRange
import com.intellij.openapi.util.Disposer
import com.intellij.psi.PsiDocumentManager
import com.intellij.ui.components.JBLabel
import com.intellij.ui.components.JBScrollPane
import com.intellij.ui.treeStructure.Tree
import com.intellij.util.Alarm
import com.jetbrains.python.psi.PyFile
import dev.pygloss.cache.ModelCacheService
import dev.pygloss.cache.Profile
import dev.pygloss.cache.VerbosityLevel
import dev.pygloss.engine.ConceptTable
import dev.pygloss.application.EnglishModelService
import dev.pygloss.model.BlockKind
import dev.pygloss.model.Concept
import dev.pygloss.model.EnglishBlock
import dev.pygloss.model.EnglishModel
import java.awt.BorderLayout
import java.awt.Component
import java.awt.FlowLayout
import javax.swing.BorderFactory
import javax.swing.JButton
import javax.swing.JComboBox
import javax.swing.JComponent
import javax.swing.DefaultListCellRenderer
import javax.swing.JList
import javax.swing.JPanel
import javax.swing.JTextArea
import javax.swing.JSplitPane
import javax.swing.SwingUtilities
import javax.swing.event.TreeSelectionEvent
import javax.swing.event.TreeSelectionListener
import javax.swing.tree.DefaultMutableTreeNode
import javax.swing.tree.DefaultTreeModel
import javax.swing.tree.TreePath
import com.intellij.util.concurrency.AppExecutorUtil
import java.util.concurrent.atomic.AtomicLong

/** Tool window panel that projects the current Python file's English outline. */
class OutlineToolWindow(private val project: Project) : Disposable {

    private val modelService: EnglishModelService get() = EnglishModelService.getInstance(project)
    private val cacheService: ModelCacheService get() = ModelCacheService.getInstance(project)
    private val profileCombo = JComboBox(Profile.entries.toTypedArray())
    private val languageCombo = JComboBox(OutlinePreferences.targetLanguages.toTypedArray())
    private val presetCombo = JComboBox(VerbosityLevel.entries.toTypedArray())
    private val refreshButton = JButton("Refresh")
    private val regenerateButton = JButton("Regenerate")
    private val tree = Tree(DefaultMutableTreeNode("No Python file"))
    private val detailArea = JTextArea()
    private val nodeByBlockId = mutableMapOf<String, DefaultMutableTreeNode>()
    private val listenedEditors = mutableSetOf<Editor>()
    private var currentModel: EnglishModel? = null
    private var currentEditor: Editor? = null
    private var ignoreSelection = false
    private var disposed = false
    private val refreshGeneration = AtomicLong()
    private val documentRefreshAlarm = Alarm(Alarm.ThreadToUse.SWING_THREAD, this)

    /** Root Swing component shown inside the tool window. */
    val component: JComponent = JPanel(BorderLayout()).apply {
        add(toolbar(), BorderLayout.NORTH)
        add(contentPane(), BorderLayout.CENTER)
    }

    init {
        loadPreferences()
        configureComboRenderers()
        configureTree()
        configureDetailArea()
        bindControls()
        subscribeToEditorChanges()
        refresh()
    }

    override fun dispose() {
        disposed = true
        currentEditor = null
        listenedEditors.clear()
        nodeByBlockId.clear()
    }

    private fun toolbar(): JComponent {
        profileCombo.toolTipText =
            "Polyglot: explains Python idioms via the closest concept in a language you already know (no AI, works offline). " +
                "Intent Summary: one-sentence summaries generated by your configured LLM."
        presetCombo.toolTipText =
            "Code: plain source · Hints: light annotations · Outline: structure-first with folds collapsed · Reader: maximum English"
        return JPanel(FlowLayout(FlowLayout.LEFT, 6, 4)).apply {
            add(JBLabel("Profile"))
            add(profileCombo)
            add(JBLabel("Target"))
            add(languageCombo)
            add(JBLabel("Preset"))
            add(presetCombo)
            add(refreshButton)
            regenerateButton.isEnabled = false
            regenerateButton.toolTipText = "Intent Summary regeneration is provided by the summary pipeline."
            add(regenerateButton)
        }
    }

    private fun contentPane(): JComponent {
        val splitPane = JSplitPane(
            JSplitPane.VERTICAL_SPLIT,
            JBScrollPane(tree),
            JBScrollPane(detailArea)
        )
        splitPane.resizeWeight = 0.72
        splitPane.border = BorderFactory.createEmptyBorder()
        return splitPane
    }

    private fun configureComboRenderers() {
        profileCombo.renderer = object : DefaultListCellRenderer() {
            override fun getListCellRendererComponent(
                list: JList<*>,
                value: Any?,
                index: Int,
                isSelected: Boolean,
                cellHasFocus: Boolean
            ): Component {
                val component = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus)
                text = when (value) {
                    Profile.POLYGLOT_LENS -> "Polyglot"
                    Profile.INTENT_SUMMARY -> "Intent Summary"
                    else -> value?.toString().orEmpty()
                }
                return component
            }
        }
        presetCombo.renderer = object : DefaultListCellRenderer() {
            override fun getListCellRendererComponent(
                list: JList<*>,
                value: Any?,
                index: Int,
                isSelected: Boolean,
                cellHasFocus: Boolean
            ): Component {
                val component = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus)
                text = when (value) {
                    VerbosityLevel.CODE -> "Code"
                    VerbosityLevel.HINTS -> "Hints"
                    VerbosityLevel.OUTLINE -> "Outline"
                    VerbosityLevel.READER -> "Reader"
                    else -> value?.toString().orEmpty()
                }
                return component
            }
        }
    }

    private fun configureTree() {
        tree.isRootVisible = false
        tree.addTreeSelectionListener(TreeSelectionListener { event ->
            if (!ignoreSelection) {
                onTreeSelection(event)
            }
            updateDetail(event.newLeadSelectionPath)
        })
    }

    private fun configureDetailArea() {
        detailArea.isEditable = false
        detailArea.lineWrap = true
        detailArea.wrapStyleWord = true
        detailArea.border = BorderFactory.createEmptyBorder(8, 8, 8, 8)
        detailArea.text = "Select an outline entry."
    }

    private fun bindControls() {
        profileCombo.addActionListener {
            OutlinePreferences.profile = profileCombo.selectedItem as Profile
            updateControlState()
        }
        languageCombo.addActionListener {
            OutlinePreferences.targetLanguage = languageCombo.selectedItem as String
        }
        presetCombo.addActionListener {
            OutlinePreferences.preset = presetCombo.selectedItem as VerbosityLevel
        }
        refreshButton.addActionListener { refresh() }
        regenerateButton.addActionListener { regenerateSelectedBlock() }
        OutlinePreferences.addListener(
            this,
            object : OutlinePreferences.Listener {
                override fun preferencesChanged() {
                    ApplicationManager.getApplication().invokeLater {
                        if (disposed) return@invokeLater
                        loadPreferences()
                        updateControlState()
                        refresh()
                    }
                }
            }
        )
    }

    private fun loadPreferences() {
        profileCombo.selectedItem = OutlinePreferences.profile
        languageCombo.selectedItem = OutlinePreferences.targetLanguage
        presetCombo.selectedItem = OutlinePreferences.preset
    }

    private fun refresh() {
        val editor = FileEditorManager.getInstance(project).selectedTextEditor
        val generation = refreshGeneration.incrementAndGet()
        currentEditor = editor
        if (editor == null) {
            currentModel = null
            renderNodes(emptyList())
            detailArea.text = "Open a Python file to view its outline."
            updateControlState()
            return
        }

        val settings = outlineSettings()
        ReadAction
            .nonBlocking<Pair<PyFile, EnglishModel>?> {
                val pyFile = editor.pythonFile() ?: return@nonBlocking null
                pyFile to modelService.getModel(pyFile, settings.profile, settings.preset)
            }
            .expireWith(this)
            .finishOnUiThread(ModalityState.defaultModalityState()) { result ->
                if (disposed || generation != refreshGeneration.get()) return@finishOnUiThread
                if (result == null) {
                    currentModel = null
                    renderNodes(emptyList())
                    detailArea.text = "Open a Python file to view its outline."
                    updateControlState()
                    return@finishOnUiThread
                }
                val (pyFile, model) = result
                updateOutline(editor, pyFile, model, settings)
            }
            .submit(AppExecutorUtil.getAppExecutorService())
    }

    private fun subscribeToEditorChanges() {
        project.messageBus.connect(this).subscribe(
            FileEditorManagerListener.FILE_EDITOR_MANAGER,
            object : FileEditorManagerListener {
                override fun selectionChanged(event: FileEditorManagerEvent) {
                    if (!disposed) refresh()
                }
            }
        )
        EditorFactory.getInstance().eventMulticaster.addDocumentListener(
            object : DocumentListener {
                override fun documentChanged(event: DocumentEvent) {
                    if (disposed || currentEditor?.document !== event.document) return
                    documentRefreshAlarm.cancelAllRequests()
                    documentRefreshAlarm.addRequest({ refresh() }, DOCUMENT_REFRESH_DELAY_MS)
                }
            },
            this
        )
    }

    private fun updateOutline(editor: Editor, pyFile: PyFile, model: EnglishModel, settings: OutlineSettings) {
        if (pyFile.project.isDisposed) return
        currentModel = model
        val statusService = IntentSummaryStatusService.getInstance(project)
        renderNodes(
            OutlineModelBuilder.build(
                model,
                settings,
                cacheService::isStale,
                statusService::isSummaryUnavailable
            )
        )
        syncCaretSelection(editor.caretModel.currentCaret)
        installCaretListener(editor)
        updateControlState()
    }

    private fun outlineSettings(): OutlineSettings {
        return OutlineSettings(
            profile = profileCombo.selectedItem as Profile,
            targetLanguage = languageCombo.selectedItem as String,
            preset = presetCombo.selectedItem as VerbosityLevel
        )
    }

    private fun renderNodes(nodes: List<OutlineNode>) {
        nodeByBlockId.clear()
        val root = DefaultMutableTreeNode("PyGloss")
        nodes.forEach { root.add(treeNode(it)) }
        ignoreSelection = true
        try {
            tree.model = DefaultTreeModel(root)
        } finally {
            ignoreSelection = false
        }
        for (row in 0 until tree.rowCount) {
            tree.expandRow(row)
        }
    }

    private fun treeNode(node: OutlineNode): DefaultMutableTreeNode {
        val treeNode = DefaultMutableTreeNode(node)
        nodeByBlockId[node.stableId] = treeNode
        node.children.forEach { treeNode.add(treeNode(it)) }
        return treeNode
    }

    private fun onTreeSelection(event: TreeSelectionEvent) {
        val path = event.newLeadSelectionPath ?: return
        if (!event.isAddedPath) return
        val node = path.lastPathComponent as? DefaultMutableTreeNode ?: return
        val outlineNode = node.userObject as? OutlineNode ?: return
        val editor = currentEditor ?: return
        val virtualFile = editor.virtualFile() ?: return
        val range = safeSelectionRange(outlineNode.range, editor.document.textLength) ?: return
        OpenFileDescriptor(project, virtualFile, range.startOffset).navigate(true)
        editor.selectionModel.setSelection(range.startOffset, range.endOffset)
        editor.caretModel.moveToOffset(range.startOffset)
    }

    private fun updateDetail(path: TreePath?) {
        val node = path?.lastPathComponent as? DefaultMutableTreeNode
        val outlineNode = node?.userObject as? OutlineNode
        detailArea.text = outlineNode?.detailText ?: "Select an outline entry."
        detailArea.caretPosition = 0
        updateControlState()
    }

    private fun selectedOutlineNode(): OutlineNode? {
        val node = tree.selectionPath?.lastPathComponent as? DefaultMutableTreeNode
        return node?.userObject as? OutlineNode
    }

    private fun regenerateSelectedBlock() {
        val editor = currentEditor ?: return
        val file = editor.pythonFile() ?: return
        val node = selectedOutlineNode() ?: return
        regenerateButton.isEnabled = false
        modelService.regenerateAtOffset(file, node.range.startOffset) {
            ApplicationManager.getApplication().invokeLater {
                if (!disposed) refresh()
            }
        }
    }

    private fun syncCaretSelection(caret: Caret) {
        val model = currentModel ?: return
        val blockId = OutlineModelBuilder.containingBlockId(model, caret.offset, outlineSettings().preset) ?: return
        val node = nodeByBlockId[blockId] ?: return
        val path = TreePath(node.path)
        ignoreSelection = true
        try {
            tree.selectionPath = path
            tree.scrollPathToVisible(path)
        } finally {
            ignoreSelection = false
        }
        updateDetail(path)
    }

    private fun installCaretListener(editor: Editor) {
        if (!listenedEditors.add(editor)) return
        editor.caretModel.addCaretListener(
            object : CaretListener {
                override fun caretPositionChanged(event: CaretEvent) {
                    if (disposed) return
                    if (editor !== currentEditor) return
                    val caret = event.caret
                    SwingUtilities.invokeLater {
                        if (!disposed) syncCaretSelection(caret)
                    }
                }
            },
            this
        )
    }

    private fun updateControlState() {
        regenerateButton.isEnabled = profileCombo.selectedItem == Profile.INTENT_SUMMARY && selectedOutlineNode() != null
    }

    private fun Editor.pythonFile(): PyFile? {
        val psiFile = PsiDocumentManager.getInstance(this@OutlineToolWindow.project).getPsiFile(document)
        return psiFile as? PyFile
    }

    private fun Editor.virtualFile() = FileDocumentManager.getInstance().getFile(document)

    private companion object {
        private const val DOCUMENT_REFRESH_DELAY_MS = 400
    }
}

/** User-visible settings that control outline projection. */
data class OutlineSettings(
    /** Active reader profile. */
    val profile: Profile,
    /** Target language for Polyglot Lens callouts. */
    val targetLanguage: String,
    /** Verbosity preset for outline shape and detail. */
    val preset: VerbosityLevel
)

/** A tree node rendered by the outline tool window. */
data class OutlineNode(
    /** Stable block identifier from the English model. */
    val stableId: String,
    /** Block kind. */
    val kind: BlockKind,
    /** Source text range for navigation and caret sync. */
    val range: TextRange,
    /** Compact label for the tree row. */
    val label: String,
    /** Projection text displayed in the detail pane. */
    val detailText: String,
    /** Whether the associated LLM summary is stale. */
    val stale: Boolean,
    /** Child outline nodes. */
    val children: List<OutlineNode>
) {
    override fun toString(): String = label
}

/** Pure outline model builder used by the UI and headless tests. */
object OutlineModelBuilder {

    /** Build visible outline nodes from [model] according to [settings]. */
    fun build(
        model: EnglishModel,
        settings: OutlineSettings,
        isStale: (String) -> Boolean = { false },
        isSummaryUnavailable: (String) -> Boolean = { false }
    ): List<OutlineNode> {
        return model.blocks.mapNotNull { toNode(it, settings, depth = 0, isStale, isSummaryUnavailable) }
    }

    /** Return a depth-first list of outline nodes. */
    fun flatten(nodes: List<OutlineNode>): List<OutlineNode> {
        val result = mutableListOf<OutlineNode>()
        fun collect(items: List<OutlineNode>) {
            items.forEach { node ->
                result.add(node)
                collect(node.children)
            }
        }
        collect(nodes)
        return result
    }

    /** Resolve [offset] to the deepest visible containing block ID. */
    fun containingBlockId(model: EnglishModel, offset: Int, preset: VerbosityLevel): String? {
        return deepestVisibleBlock(model.blocks, offset, preset, depth = 0)?.stableId
    }

    private fun toNode(
        block: EnglishBlock,
        settings: OutlineSettings,
        depth: Int,
        isStale: (String) -> Boolean,
        isSummaryUnavailable: (String) -> Boolean
    ): OutlineNode? {
        if (!isVisible(block, settings.preset, depth)) return null
        val children = block.children.mapNotNull { toNode(it, settings, depth + 1, isStale, isSummaryUnavailable) }
        val stale = isStale(block.stableId)
        return OutlineNode(
            stableId = block.stableId,
            kind = block.kind,
            range = block.textRange,
            label = labelFor(block),
            detailText = detailFor(block, settings, stale, isSummaryUnavailable(block.psiHash)),
            stale = stale,
            children = children
        )
    }

    private fun deepestVisibleBlock(
        blocks: List<EnglishBlock>,
        offset: Int,
        preset: VerbosityLevel,
        depth: Int
    ): EnglishBlock? {
        return blocks
            .filter { it.textRange.containsOffset(offset) && isVisible(it, preset, depth) }
            .map { block ->
                deepestVisibleBlock(block.children, offset, preset, depth + 1) ?: block
            }
            .maxByOrNull { it.textRange.startOffset }
    }

    private fun isVisible(block: EnglishBlock, preset: VerbosityLevel, depth: Int): Boolean {
        return when (preset) {
            VerbosityLevel.CODE -> depth == 0 && block.kind in setOf(BlockKind.CLASS, BlockKind.FUNCTION)
            VerbosityLevel.HINTS -> block.kind != BlockKind.COMPREHENSION
            VerbosityLevel.OUTLINE -> block.kind != BlockKind.COMPREHENSION || block.concepts.isNotEmpty()
            VerbosityLevel.READER -> true
        }
    }

    private fun labelFor(block: EnglishBlock): String {
        val name = block.skeleton.substringAfter("name=", "").substringBefore("|").takeIf { it.isNotBlank() }
        return if (name == null) {
            block.kind.name.lowercase()
        } else {
            "${block.kind.name.lowercase()} $name"
        }
    }

    private fun detailFor(
        block: EnglishBlock,
        settings: OutlineSettings,
        stale: Boolean,
        summaryUnavailable: Boolean
    ): String {
        if (settings.preset == VerbosityLevel.CODE) return ""
        val header = readableHeader(block.kind, block.skeleton)
        val body = when (settings.profile) {
            Profile.POLYGLOT_LENS -> analogyText(block, settings.targetLanguage)
            Profile.INTENT_SUMMARY -> summaryText(block, stale, summaryUnavailable)
        }
        return listOf(header, body).filter { it.isNotBlank() }.joinToString("\n\n")
    }

    /** Convert deterministic skeleton facts into a user-readable detail header. */
    fun readableHeader(kind: BlockKind, skeleton: String): String {
        val facts = skeletonFacts(skeleton)
        return when (kind) {
            BlockKind.FUNCTION -> functionHeader(facts)
            BlockKind.CLASS -> classHeader(facts)
            BlockKind.IF -> "if block"
            BlockKind.FOR -> "for loop"
            BlockKind.WHILE -> "while loop"
            BlockKind.WITH -> "with block"
            BlockKind.TRY -> "try block"
            BlockKind.COMPREHENSION -> "comprehension"
            BlockKind.MODULE -> "module"
        }
    }

    private fun analogyText(block: EnglishBlock, language: String): String {
        if (block.concepts.isEmpty()) return "No analogy callouts for this block."
        return block.concepts
            .sortedBy(Concept::name)
            .mapNotNull { concept ->
                ConceptTable.lookup(concept, language)?.let { entry ->
                    "${concept.name.lowercase()}: Closest analogy: ${entry.closestAnalogy} " +
                        "(${entry.confidenceTier.name.lowercase()} confidence). Caveat: ${entry.caveat}"
                }
            }
            .joinToString("\n")
            .ifBlank { "No analogy callouts for this block." }
    }

    private fun summaryText(block: EnglishBlock, stale: Boolean, unavailable: Boolean): String {
        val badge = if (stale) "[stale] " else ""
        val summary = block.summary ?: if (unavailable) {
            "Summary unavailable — check the LLM provider in Settings → Tools → PyGloss."
        } else {
            "Summary not generated yet."
        }
        return "$badge$summary"
    }

    private fun skeletonFacts(skeleton: String): Map<String, String> {
        return skeleton.split("|")
            .mapNotNull { fact ->
                val key = fact.substringBefore("=", "")
                val value = fact.substringAfter("=", "")
                if (key.isBlank()) null else key to value
            }
            .toMap()
    }

    private fun functionHeader(facts: Map<String, String>): String {
        val name = facts["name"].orEmpty().ifBlank { "function" }
        val params = commaList(facts["params"])
        val asyncPrefix = if (facts["async"] == "true") "async " else ""
        val decorated = decoratorsText(facts["decorators"])
        return "${asyncPrefix}function $name($params)$decorated"
    }

    private fun classHeader(facts: Map<String, String>): String {
        val name = facts["name"].orEmpty().ifBlank { "class" }
        val bases = commaList(facts["bases"]).takeIf { it.isNotBlank() }?.let { " (extends $it)" }.orEmpty()
        val decorated = decoratorsText(facts["decorators"])
        return "class $name$bases$decorated"
    }

    private fun decoratorsText(rawDecorators: String?): String {
        val decorators = rawDecorators.orEmpty()
            .split(",")
            .mapNotNull { it.trim().takeIf(String::isNotBlank) }
            .joinToString(", ") { "@$it" }
        return if (decorators.isBlank()) "" else " — decorated with $decorators"
    }

    private fun commaList(raw: String?): String {
        return raw.orEmpty()
            .split(",")
            .mapNotNull { it.trim().takeIf(String::isNotBlank) }
            .joinToString(", ")
    }
}

/** Persisted outline preferences used by toolbar controls and preset actions. */
object OutlinePreferences {

    /** Supported Polyglot Lens target languages. */
    val targetLanguages: List<String> = listOf("JS", "Java", "Go", "C#")

    private const val PROFILE_KEY = "dev.pygloss.outline.profile"
    private const val TARGET_LANGUAGE_KEY = "dev.pygloss.outline.targetLanguage"
    private const val PRESET_KEY = "dev.pygloss.outline.preset"
    private val listeners = java.util.concurrent.CopyOnWriteArrayList<Listener>()

    /** Listener notified after a persisted outline preference changes. */
    interface Listener {
        fun preferencesChanged()
    }

    /** Persisted reader profile. */
    var profile: Profile
        get() = enumValueOrDefault(PROFILE_KEY, Profile.POLYGLOT_LENS)
        set(value) = update(profile = value)

    /** Persisted target language. */
    var targetLanguage: String
        get() = properties().getValue(TARGET_LANGUAGE_KEY, "JS").takeIf { it in targetLanguages } ?: "JS"
        set(value) = update(targetLanguage = value)

    /** Persisted verbosity preset. */
    var preset: VerbosityLevel
        get() = enumValueOrDefault(PRESET_KEY, VerbosityLevel.HINTS)
        set(value) = update(preset = value)

    /** Persist outline preferences as one change and refresh open rendering surfaces. */
    fun update(
        profile: Profile = this.profile,
        targetLanguage: String = this.targetLanguage,
        preset: VerbosityLevel = this.preset
    ) {
        val normalizedTargetLanguage = targetLanguage.takeIf { it in targetLanguages } ?: "JS"
        val changed = profile != this.profile ||
            normalizedTargetLanguage != this.targetLanguage ||
            preset != this.preset
        if (!changed) return

        val properties = properties()
        properties.setValue(PROFILE_KEY, profile.name)
        properties.setValue(TARGET_LANGUAGE_KEY, normalizedTargetLanguage)
        properties.setValue(PRESET_KEY, preset.name)
        notifyChanged()
    }

    /** Register a listener that is removed with [parentDisposable]. */
    fun addListener(parentDisposable: Disposable, listener: Listener) {
        listeners.add(listener)
        Disposer.register(parentDisposable) { listeners.remove(listener) }
    }

    private inline fun <reified T : Enum<T>> enumValueOrDefault(key: String, default: T): T {
        val raw = properties().getValue(key, default.name)
        return runCatching { enumValueOf<T>(raw) }.getOrDefault(default)
    }

    private fun properties(): PropertiesComponent {
        return ApplicationManager.getApplication().getService(PropertiesComponent::class.java)
    }

    private fun notifyChanged() {
        listeners.forEach { it.preferencesChanged() }
        PyGlossRefresher.refreshAllProjects()
    }
}

/** Return [range] only when it is valid for the current document length. */
fun safeSelectionRange(range: TextRange, documentLength: Int): TextRange? {
    return range.takeIf {
        documentLength >= 0 &&
            it.startOffset >= 0 &&
            it.endOffset >= it.startOffset &&
            it.startOffset <= documentLength &&
            it.endOffset <= documentLength
    }
}
